name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['11', '17']
        os: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Maven tests with Allure
      run: |
        mvn clean test
        mvn allure:report

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-java${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          target/site/allure-maven-plugin/
        retention-days: 5

    - name: Generate Allure Report
      if: always()
      uses: simple-elf/allure-report-action@v2
      with:
        allure_results: target/allure-results
        enable_charts: true

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-java${{ matrix.java-version }}
        path: target/site/allure-maven-plugin
        retention-days: 5
